//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MiniProjekatKlas.KontrolerInterfejsa.localhost {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServisSoap", Namespace="localhost")]
    public partial class Servis : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback VratiNovuSifruZaProizvodOperationCompleted;
        
        private System.Threading.SendOrPostCallback VratiSveProizvodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UbaciProizvodOperationCompleted;
        
        private System.Threading.SendOrPostCallback AzurirajProizvodOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObrisiProizvodOperationCompleted;
        
        private System.Threading.SendOrPostCallback VratiProizvodOperationCompleted;
        
        private System.Threading.SendOrPostCallback VratiNovuSifruZaRacunOperationCompleted;
        
        private System.Threading.SendOrPostCallback VratiRacunOperationCompleted;
        
        private System.Threading.SendOrPostCallback UbaciRacunOperationCompleted;
        
        private System.Threading.SendOrPostCallback AzurirajRacunOperationCompleted;
        
        private System.Threading.SendOrPostCallback StornirajRacunOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Servis() {
            this.Url = global::MiniProjekatKlas.KontrolerInterfejsa.Properties.Settings.Default.KontrolerInterfejsa_localhost_Servis;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event VratiNovuSifruZaProizvodCompletedEventHandler VratiNovuSifruZaProizvodCompleted;
        
        /// <remarks/>
        public event VratiSveProizvodeCompletedEventHandler VratiSveProizvodeCompleted;
        
        /// <remarks/>
        public event UbaciProizvodCompletedEventHandler UbaciProizvodCompleted;
        
        /// <remarks/>
        public event AzurirajProizvodCompletedEventHandler AzurirajProizvodCompleted;
        
        /// <remarks/>
        public event ObrisiProizvodCompletedEventHandler ObrisiProizvodCompleted;
        
        /// <remarks/>
        public event VratiProizvodCompletedEventHandler VratiProizvodCompleted;
        
        /// <remarks/>
        public event VratiNovuSifruZaRacunCompletedEventHandler VratiNovuSifruZaRacunCompleted;
        
        /// <remarks/>
        public event VratiRacunCompletedEventHandler VratiRacunCompleted;
        
        /// <remarks/>
        public event UbaciRacunCompletedEventHandler UbaciRacunCompleted;
        
        /// <remarks/>
        public event AzurirajRacunCompletedEventHandler AzurirajRacunCompleted;
        
        /// <remarks/>
        public event StornirajRacunCompletedEventHandler StornirajRacunCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("localhost/VratiNovuSifruZaProizvod", RequestNamespace="localhost", ResponseNamespace="localhost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int VratiNovuSifruZaProizvod() {
            object[] results = this.Invoke("VratiNovuSifruZaProizvod", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void VratiNovuSifruZaProizvodAsync() {
            this.VratiNovuSifruZaProizvodAsync(null);
        }
        
        /// <remarks/>
        public void VratiNovuSifruZaProizvodAsync(object userState) {
            if ((this.VratiNovuSifruZaProizvodOperationCompleted == null)) {
                this.VratiNovuSifruZaProizvodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVratiNovuSifruZaProizvodOperationCompleted);
            }
            this.InvokeAsync("VratiNovuSifruZaProizvod", new object[0], this.VratiNovuSifruZaProizvodOperationCompleted, userState);
        }
        
        private void OnVratiNovuSifruZaProizvodOperationCompleted(object arg) {
            if ((this.VratiNovuSifruZaProizvodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VratiNovuSifruZaProizvodCompleted(this, new VratiNovuSifruZaProizvodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("localhost/VratiSveProizvode", RequestNamespace="localhost", ResponseNamespace="localhost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Proizvod[] VratiSveProizvode(Proizvod proizvod) {
            object[] results = this.Invoke("VratiSveProizvode", new object[] {
                        proizvod});
            return ((Proizvod[])(results[0]));
        }
        
        /// <remarks/>
        public void VratiSveProizvodeAsync(Proizvod proizvod) {
            this.VratiSveProizvodeAsync(proizvod, null);
        }
        
        /// <remarks/>
        public void VratiSveProizvodeAsync(Proizvod proizvod, object userState) {
            if ((this.VratiSveProizvodeOperationCompleted == null)) {
                this.VratiSveProizvodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVratiSveProizvodeOperationCompleted);
            }
            this.InvokeAsync("VratiSveProizvode", new object[] {
                        proizvod}, this.VratiSveProizvodeOperationCompleted, userState);
        }
        
        private void OnVratiSveProizvodeOperationCompleted(object arg) {
            if ((this.VratiSveProizvodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VratiSveProizvodeCompleted(this, new VratiSveProizvodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("localhost/UbaciProizvod", RequestNamespace="localhost", ResponseNamespace="localhost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UbaciProizvod(Proizvod proizvod) {
            object[] results = this.Invoke("UbaciProizvod", new object[] {
                        proizvod});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UbaciProizvodAsync(Proizvod proizvod) {
            this.UbaciProizvodAsync(proizvod, null);
        }
        
        /// <remarks/>
        public void UbaciProizvodAsync(Proizvod proizvod, object userState) {
            if ((this.UbaciProizvodOperationCompleted == null)) {
                this.UbaciProizvodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUbaciProizvodOperationCompleted);
            }
            this.InvokeAsync("UbaciProizvod", new object[] {
                        proizvod}, this.UbaciProizvodOperationCompleted, userState);
        }
        
        private void OnUbaciProizvodOperationCompleted(object arg) {
            if ((this.UbaciProizvodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UbaciProizvodCompleted(this, new UbaciProizvodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("localhost/AzurirajProizvod", RequestNamespace="localhost", ResponseNamespace="localhost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AzurirajProizvod(Proizvod proizvod) {
            object[] results = this.Invoke("AzurirajProizvod", new object[] {
                        proizvod});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AzurirajProizvodAsync(Proizvod proizvod) {
            this.AzurirajProizvodAsync(proizvod, null);
        }
        
        /// <remarks/>
        public void AzurirajProizvodAsync(Proizvod proizvod, object userState) {
            if ((this.AzurirajProizvodOperationCompleted == null)) {
                this.AzurirajProizvodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAzurirajProizvodOperationCompleted);
            }
            this.InvokeAsync("AzurirajProizvod", new object[] {
                        proizvod}, this.AzurirajProizvodOperationCompleted, userState);
        }
        
        private void OnAzurirajProizvodOperationCompleted(object arg) {
            if ((this.AzurirajProizvodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AzurirajProizvodCompleted(this, new AzurirajProizvodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("localhost/ObrisiProizvod", RequestNamespace="localhost", ResponseNamespace="localhost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int ObrisiProizvod(Proizvod proizvod) {
            object[] results = this.Invoke("ObrisiProizvod", new object[] {
                        proizvod});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ObrisiProizvodAsync(Proizvod proizvod) {
            this.ObrisiProizvodAsync(proizvod, null);
        }
        
        /// <remarks/>
        public void ObrisiProizvodAsync(Proizvod proizvod, object userState) {
            if ((this.ObrisiProizvodOperationCompleted == null)) {
                this.ObrisiProizvodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObrisiProizvodOperationCompleted);
            }
            this.InvokeAsync("ObrisiProizvod", new object[] {
                        proizvod}, this.ObrisiProizvodOperationCompleted, userState);
        }
        
        private void OnObrisiProizvodOperationCompleted(object arg) {
            if ((this.ObrisiProizvodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObrisiProizvodCompleted(this, new ObrisiProizvodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("localhost/VratiProizvod", RequestNamespace="localhost", ResponseNamespace="localhost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Proizvod VratiProizvod(Proizvod proizvod) {
            object[] results = this.Invoke("VratiProizvod", new object[] {
                        proizvod});
            return ((Proizvod)(results[0]));
        }
        
        /// <remarks/>
        public void VratiProizvodAsync(Proizvod proizvod) {
            this.VratiProizvodAsync(proizvod, null);
        }
        
        /// <remarks/>
        public void VratiProizvodAsync(Proizvod proizvod, object userState) {
            if ((this.VratiProizvodOperationCompleted == null)) {
                this.VratiProizvodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVratiProizvodOperationCompleted);
            }
            this.InvokeAsync("VratiProizvod", new object[] {
                        proizvod}, this.VratiProizvodOperationCompleted, userState);
        }
        
        private void OnVratiProizvodOperationCompleted(object arg) {
            if ((this.VratiProizvodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VratiProizvodCompleted(this, new VratiProizvodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("localhost/VratiNovuSifruZaRacun", RequestNamespace="localhost", ResponseNamespace="localhost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int VratiNovuSifruZaRacun(Racun rac) {
            object[] results = this.Invoke("VratiNovuSifruZaRacun", new object[] {
                        rac});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void VratiNovuSifruZaRacunAsync(Racun rac) {
            this.VratiNovuSifruZaRacunAsync(rac, null);
        }
        
        /// <remarks/>
        public void VratiNovuSifruZaRacunAsync(Racun rac, object userState) {
            if ((this.VratiNovuSifruZaRacunOperationCompleted == null)) {
                this.VratiNovuSifruZaRacunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVratiNovuSifruZaRacunOperationCompleted);
            }
            this.InvokeAsync("VratiNovuSifruZaRacun", new object[] {
                        rac}, this.VratiNovuSifruZaRacunOperationCompleted, userState);
        }
        
        private void OnVratiNovuSifruZaRacunOperationCompleted(object arg) {
            if ((this.VratiNovuSifruZaRacunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VratiNovuSifruZaRacunCompleted(this, new VratiNovuSifruZaRacunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("localhost/VratiRacun", RequestNamespace="localhost", ResponseNamespace="localhost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Racun VratiRacun(Racun rac) {
            object[] results = this.Invoke("VratiRacun", new object[] {
                        rac});
            return ((Racun)(results[0]));
        }
        
        /// <remarks/>
        public void VratiRacunAsync(Racun rac) {
            this.VratiRacunAsync(rac, null);
        }
        
        /// <remarks/>
        public void VratiRacunAsync(Racun rac, object userState) {
            if ((this.VratiRacunOperationCompleted == null)) {
                this.VratiRacunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVratiRacunOperationCompleted);
            }
            this.InvokeAsync("VratiRacun", new object[] {
                        rac}, this.VratiRacunOperationCompleted, userState);
        }
        
        private void OnVratiRacunOperationCompleted(object arg) {
            if ((this.VratiRacunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VratiRacunCompleted(this, new VratiRacunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("localhost/UbaciRacun", RequestNamespace="localhost", ResponseNamespace="localhost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int UbaciRacun(Racun rac) {
            object[] results = this.Invoke("UbaciRacun", new object[] {
                        rac});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void UbaciRacunAsync(Racun rac) {
            this.UbaciRacunAsync(rac, null);
        }
        
        /// <remarks/>
        public void UbaciRacunAsync(Racun rac, object userState) {
            if ((this.UbaciRacunOperationCompleted == null)) {
                this.UbaciRacunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUbaciRacunOperationCompleted);
            }
            this.InvokeAsync("UbaciRacun", new object[] {
                        rac}, this.UbaciRacunOperationCompleted, userState);
        }
        
        private void OnUbaciRacunOperationCompleted(object arg) {
            if ((this.UbaciRacunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UbaciRacunCompleted(this, new UbaciRacunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("localhost/AzurirajRacun", RequestNamespace="localhost", ResponseNamespace="localhost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AzurirajRacun(Racun rac) {
            object[] results = this.Invoke("AzurirajRacun", new object[] {
                        rac});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AzurirajRacunAsync(Racun rac) {
            this.AzurirajRacunAsync(rac, null);
        }
        
        /// <remarks/>
        public void AzurirajRacunAsync(Racun rac, object userState) {
            if ((this.AzurirajRacunOperationCompleted == null)) {
                this.AzurirajRacunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAzurirajRacunOperationCompleted);
            }
            this.InvokeAsync("AzurirajRacun", new object[] {
                        rac}, this.AzurirajRacunOperationCompleted, userState);
        }
        
        private void OnAzurirajRacunOperationCompleted(object arg) {
            if ((this.AzurirajRacunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AzurirajRacunCompleted(this, new AzurirajRacunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("localhost/StornirajRacun", RequestNamespace="localhost", ResponseNamespace="localhost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int StornirajRacun(Racun rac) {
            object[] results = this.Invoke("StornirajRacun", new object[] {
                        rac});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void StornirajRacunAsync(Racun rac) {
            this.StornirajRacunAsync(rac, null);
        }
        
        /// <remarks/>
        public void StornirajRacunAsync(Racun rac, object userState) {
            if ((this.StornirajRacunOperationCompleted == null)) {
                this.StornirajRacunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStornirajRacunOperationCompleted);
            }
            this.InvokeAsync("StornirajRacun", new object[] {
                        rac}, this.StornirajRacunOperationCompleted, userState);
        }
        
        private void OnStornirajRacunOperationCompleted(object arg) {
            if ((this.StornirajRacunCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StornirajRacunCompleted(this, new StornirajRacunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="localhost")]
    public partial class Proizvod {
        
        private int sifraProizvodaField;
        
        private string nazivField;
        
        private double cenaField;
        
        private string rokTrajanjaField;
        
        /// <remarks/>
        public int SifraProizvoda {
            get {
                return this.sifraProizvodaField;
            }
            set {
                this.sifraProizvodaField = value;
            }
        }
        
        /// <remarks/>
        public string Naziv {
            get {
                return this.nazivField;
            }
            set {
                this.nazivField = value;
            }
        }
        
        /// <remarks/>
        public double Cena {
            get {
                return this.cenaField;
            }
            set {
                this.cenaField = value;
            }
        }
        
        /// <remarks/>
        public string RokTrajanja {
            get {
                return this.rokTrajanjaField;
            }
            set {
                this.rokTrajanjaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="localhost")]
    public partial class StavkaRacuna {
        
        private int brojRacunaField;
        
        private int redniBrojField;
        
        private int kolicinaField;
        
        private double vrednostField;
        
        private int sifraProizvodaField;
        
        /// <remarks/>
        public int BrojRacuna {
            get {
                return this.brojRacunaField;
            }
            set {
                this.brojRacunaField = value;
            }
        }
        
        /// <remarks/>
        public int RedniBroj {
            get {
                return this.redniBrojField;
            }
            set {
                this.redniBrojField = value;
            }
        }
        
        /// <remarks/>
        public int Kolicina {
            get {
                return this.kolicinaField;
            }
            set {
                this.kolicinaField = value;
            }
        }
        
        /// <remarks/>
        public double Vrednost {
            get {
                return this.vrednostField;
            }
            set {
                this.vrednostField = value;
            }
        }
        
        /// <remarks/>
        public int SifraProizvoda {
            get {
                return this.sifraProizvodaField;
            }
            set {
                this.sifraProizvodaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="localhost")]
    public partial class Racun {
        
        private int brojRacunaField;
        
        private double ukupnaVrednostField;
        
        private bool storniranField;
        
        private StavkaRacuna[] stavkeRacunaField;
        
        /// <remarks/>
        public int BrojRacuna {
            get {
                return this.brojRacunaField;
            }
            set {
                this.brojRacunaField = value;
            }
        }
        
        /// <remarks/>
        public double UkupnaVrednost {
            get {
                return this.ukupnaVrednostField;
            }
            set {
                this.ukupnaVrednostField = value;
            }
        }
        
        /// <remarks/>
        public bool Storniran {
            get {
                return this.storniranField;
            }
            set {
                this.storniranField = value;
            }
        }
        
        /// <remarks/>
        public StavkaRacuna[] StavkeRacuna {
            get {
                return this.stavkeRacunaField;
            }
            set {
                this.stavkeRacunaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void VratiNovuSifruZaProizvodCompletedEventHandler(object sender, VratiNovuSifruZaProizvodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VratiNovuSifruZaProizvodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VratiNovuSifruZaProizvodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void VratiSveProizvodeCompletedEventHandler(object sender, VratiSveProizvodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VratiSveProizvodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VratiSveProizvodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Proizvod[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Proizvod[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UbaciProizvodCompletedEventHandler(object sender, UbaciProizvodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UbaciProizvodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UbaciProizvodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AzurirajProizvodCompletedEventHandler(object sender, AzurirajProizvodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AzurirajProizvodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AzurirajProizvodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ObrisiProizvodCompletedEventHandler(object sender, ObrisiProizvodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObrisiProizvodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObrisiProizvodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void VratiProizvodCompletedEventHandler(object sender, VratiProizvodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VratiProizvodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VratiProizvodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Proizvod Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Proizvod)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void VratiNovuSifruZaRacunCompletedEventHandler(object sender, VratiNovuSifruZaRacunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VratiNovuSifruZaRacunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VratiNovuSifruZaRacunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void VratiRacunCompletedEventHandler(object sender, VratiRacunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VratiRacunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal VratiRacunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Racun Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Racun)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UbaciRacunCompletedEventHandler(object sender, UbaciRacunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UbaciRacunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UbaciRacunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void AzurirajRacunCompletedEventHandler(object sender, AzurirajRacunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AzurirajRacunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AzurirajRacunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void StornirajRacunCompletedEventHandler(object sender, StornirajRacunCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StornirajRacunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StornirajRacunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591